Repository Joehoel/compagnon, pull requests merged in 2022-09, with the labels that each got.

#85 fix: gif function
  package.json
  pnpm-lock.yaml
  src/commands/fun/gif.ts
  src/lib/helpers.ts
Labels: bug

#88 fix: global swear count
  src/commands/swears.ts
Labels: bug

#89 feat: add uwu command
  package.json
  pnpm-lock.yaml
  src/commands/uwu.ts
Labels: enhancement

#90 refactor: swear words
  data/scheldwoorden-en.txt
  data/scheldwoorden-nl.txt
  data/scheldwoorden.txt
  package-lock.json
  package.json
  pnpm-lock.yaml
  src/modules/swears.ts
Labels: formatting
